name: 'spreadsheets-push'
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  spreadsheets:
    name: 'Spreadsheets push'
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'qa/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Spreadsheets push
        uses: ./.github/actions/spreadsheets-push-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
